{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonUI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/UnifiedLogging\/documentation\/UnifiedLogging\/ErrorSource","preciseIdentifier":"s:14UnifiedLogging11ErrorSourceV","text":"ErrorSource"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/unifiedlogging\/errorsource\/nonui"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/UnifiedLogging\/documentation\/UnifiedLogging\/ErrorSource\/nonUI","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Use this value for background errors that will not be shown to the user."},{"type":"text","text":" "},{"type":"text","text":"It is expected that this error has a "},{"type":"codeVoice","code":"silent"},{"type":"text","text":" presentation style."}],"kind":"symbol","metadata":{"role":"symbol","title":"nonUI","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonUI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorSource","preciseIdentifier":"s:14UnifiedLogging11ErrorSourceV"}],"symbolKind":"property","externalID":"s:14UnifiedLogging11ErrorSourceV5nonUIACvpZ","extendedModule":"UnifiedLogging","modules":[{"name":"UnifiedLogging"}]},"hierarchy":{"paths":[["doc:\/\/UnifiedLogging\/documentation\/UnifiedLogging","doc:\/\/UnifiedLogging\/documentation\/UnifiedLogging\/ErrorSource"]]},"references":{"doc://UnifiedLogging/documentation/UnifiedLogging/ErrorSource":{"role":"symbol","title":"ErrorSource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorSource"}],"abstract":[{"type":"text","text":"A structure representing the source of an error."}],"identifier":"doc:\/\/UnifiedLogging\/documentation\/UnifiedLogging\/ErrorSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorSource"}],"url":"\/documentation\/unifiedlogging\/errorsource"},"doc://UnifiedLogging/documentation/UnifiedLogging":{"role":"collection","title":"UnifiedLogging","abstract":[{"type":"text","text":"A Logging API for Swift and Apple platforms."}],"identifier":"doc:\/\/UnifiedLogging\/documentation\/UnifiedLogging","kind":"symbol","type":"topic","url":"\/documentation\/unifiedlogging"},"doc://UnifiedLogging/documentation/UnifiedLogging/ErrorSource/nonUI":{"role":"symbol","title":"nonUI","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonUI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorSource","preciseIdentifier":"s:14UnifiedLogging11ErrorSourceV"}],"abstract":[{"type":"text","text":"Use this value for background errors that will not be shown to the user."},{"type":"text","text":" "},{"type":"text","text":"It is expected that this error has a "},{"type":"codeVoice","code":"silent"},{"type":"text","text":" presentation style."}],"identifier":"doc:\/\/UnifiedLogging\/documentation\/UnifiedLogging\/ErrorSource\/nonUI","kind":"symbol","type":"topic","url":"\/documentation\/unifiedlogging\/errorsource\/nonui"}}}